# docs: https://docs.docker.com/compose/compose-file/
name: inception

networks:
  inception:
    driver: bridge

# https://docs.docker.com/reference/cli/docker/volume/create/#opt
volumes:
  wp-database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wp-database
  wp-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wp-files

services:
  nginx:
    build: ./nginx
    container_name: nginx-container
    ports: [443:443]
    depends_on:
      wordpress:
        condition: service_healthy
        required: true
    volumes: [wp-files:/var/www/html/inception]
    networks: [inception]
    restart: always

  wordpress:
    build: ./wordpress
    container_name: wordpress-container
    depends_on:
      mariadb:
        condition: service_healthy
        required: true
    volumes: [wp-files:/var/www/html/inception]
    networks: [inception]
    restart: always

  mariadb:
    build: ./mariadb
    container_name: mariadb-container
    volumes: [wp-database:/var/lib/mysql]
    networks: [inception]
    restart: always
