name: inception

networks:
  inception:
    driver: bridge

# volumes:
#   wp-database:
#   wp-website:

services:
  nginx:
    build: ./nginx
    container_name: nginx-container
    ports: [443:443]
    depends_on:
      wordpress:
        condition: service_healthy
        required: true
    networks: [inception]
    restart: always

  wordpress:
    build: ./wordpress
    container_name: wordpress-container
    # ports: [9000:9000]
    depends_on:
      mariadb:
        condition: service_healthy
        required: true
    networks: [inception]
    restart: always

  mariadb:
    build: ./mariadb
    # volumes: [wp-database: /usr/local/mysql/var]
    container_name: mariadb-container
    # ports: [3306:3306]
    networks: [inception]
    restart: always
